; PlatformIO Project Configuration
; Waveshare ESP32-S3-Touch-AMOLED-1.75C
; 466x466 Round AMOLED — Animated Face Display

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
upload_port = COM5
monitor_port = COM5
monitor_speed = 115200

; Flash & PSRAM
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = dio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = default_16MB.csv

; Libraries
lib_deps =
    moononournation/GFX Library for Arduino@1.5.6
    lewisxhe/XPowersLib@^0.2.6
    h2zero/NimBLE-Arduino@^1.4.1

build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCONFIG_BT_NIMBLE_ROLE_PERIPHERAL
    -DCONFIG_BT_NIMBLE_ROLE_BROADCASTER
    -DCONFIG_BT_NIMBLE_MAX_CONNECTIONS=1
